AusDTO/dto-digitalmarketplace-supplier-frontend

app/main/errors.py, config.py, tests/app/helpers.py
the login will be at /marketplace (buyer fe)
=> fix login path

app/main/__init__.py, app/main/helpers/briefs.py, app/main/views/suppliers.py, app/templates/briefs/clarification_question.html, app/templates/emails/brief_clarification_question.html, app/templates/emails/brief_clarification_question_confirmation.html, app/templates/suppliers/_contributors.html, bower.json, config.py, tests/app/helpers.py, tests/app/main/test_briefs.py, tests/app/main/test_login.py, tests/app/main/test_services.py, tests/app/main/test_suppliers.py
Our suppliers don't have services at the moment, so some service-based
logic has been removed.
=> Misc. fixes to make supplier frontend work for us

app/main/helpers/__init__.py, app/main/views/suppliers.py, app/templates/suppliers/dashboard.html, tests/app/main/test_suppliers.py
We expect to add some of this back later, but with changes.
=> Disable some broken/unused functionality in the supplier frontend

.gitignore, config.py
We had to do this with buyer frontend as well.
=> do not log to file on prod

app/assets/scss/_navigation.scss, app/assets/scss/_page-header.scss, app/assets/scss/_typography.scss, app/templates/_footer_top.html, app/templates/main_template.html, app/templates/suppliers/dashboard.html, bower.json, tests/app/main/test_briefs.py
Updated styles and main template with the latest stylings and formatting from buyer frontend.
=> Update main template

app/templates/main_template.html
Switch back to "private beta" badge.
=> Badge label change

app/assets/scss/_buyerpages.scss, app/assets/scss/_forms.scss, app/assets/scss/_tables.scss, app/assets/scss/_typography.scss, app/templates/briefs/brief_response.html, bower.json
Tweaks to styles and layout for brief response.
=> Styling tweaks for brief responses

app/__init__.py, app/main/views/briefs.py, app/templates/_footer_top.html, app/templates/main_template.html, app/templates/suppliers/dashboard.html, config.py, requirements.txt
Static assets are still served from /marketplace/suppliers/static, which
needs extra routing.
=> Make the Supplier frontend work from /

app/__init__.py, app/main/helpers/users.py, app/main/views/login.py, app/main/views/suppliers.py, app/templates/auth/create_user.html, app/templates/auth/create_user_error.html, config.py, requirements_for_test.txt, tests/app/main/test_login.py, tests/app/main/test_suppliers.py
Main change is to use the new URL token system and add the supplier
account user's name in the (encrypted) token.
=> Prepare supplier account creation

app/main/views/login.py
/sellers/create-user/fake-token renders the page with dummy data.
This is to help frontend devs do styling without needing invites.
=> Support a fake URL supplier invite token in debug mode

app/templates/emails/brief_clarification_question.html
=> Email fixes

app/assets/scss/_accordions.scss, app/assets/scss/_block-elements.scss, app/assets/scss/_buyerpages.scss, app/assets/scss/_forms.scss, app/assets/scss/_grid-settings.scss, app/assets/scss/_lists.scss, app/assets/scss/_page-header.scss, app/assets/scss/_print.scss, app/assets/scss/_search.scss, app/assets/scss/_typography.scss, app/assets/scss/application-ie8.scss, app/assets/scss/application-print.scss, app/assets/scss/application.scss, app/assets/scss/gov-au-ui-kit/_colours.scss
- Latest CSS from Buyer Frontend applied
=> Copied latest CSS from Buyer Frontend to Seller Frontend.

app/__init__.py, app/main/views/login.py, app/main/views/services.py, app/main/views/users.py, app/templates/suppliers/_contributors.html, application.py, config.py, tests/app/helpers.py, tests/app/main/test_login.py
Reverts AusDTO/dto-digitalmarketplace-supplier-frontend#45
=> Revert "Add contributor"

app/assets/scss/_dashboard.scss, app/assets/scss/application.scss, app/templates/suppliers/dashboard.html, app/templates/users/list_users.html
- Fixed seller dashboard page styling the invite/remove contributors link.
- Fixed add remove contributors page styling the invite/remove contributors link.
=> Styled invite/remove contributors link.

app/assets/scss/_links.scss, app/assets/scss/_typography.scss, app/templates/suppliers/_contributors.html, app/templates/suppliers/dashboard.html, app/templates/users/list_users.html, bower.json
- Styled contributor flow functionality.
=> Added styling for contributors functionality.

app/invites/__init__.py, requirements.txt, tests/app/invites/test_invites.py
* Add a command for listing unclaimed invites
* Organise commands using a submanager
* Add some more docs
=> Improvements to supplier invite handling

app/templates/suppliers/_account.html
Add "View your profile" link on seller dashboard.
=> View your profile link

app/main/forms/suppliers.py, app/main/views/suppliers.py, app/templates/suppliers/edit_supplier.html, requirements.txt, tests/app/main/test_suppliers.py
- only allow editing of summary and contact details
- edit did not work with previous changes to API
=> fix edit supplier details

app/assets/scss/_buyerpages.scss, app/templates/suppliers/edit_supplier.html
Added styles to edit seller profile page.
=> Styling edit seller profile page

application.py, requirements.txt, tests/__init__.py, tests/app/helpers.py, tests/app/main/test_login.py
Two fixes needed:
* Handling of feature flags config in utils
* Managing terms_accepted_at field for users
=> Upgrade utils

requirements.txt
Latest/greatest date formats on supplier frontend too
=> utils version bump

app/main/views/suppliers.py, requirements.txt, tests/app/main/test_suppliers.py
Dependent on https://github.com/AusDTO/dto-digitalmarketplace-utils/pull/56
=> Add new supplier profile editor

app/main/helpers/users.py, app/main/views/signup.py, app/templates/auth/seller-signup-email-sent.html, app/templates/emails/create_seller_user_email.html, config.py, tests/app/main/test_signup.py
- validate applicant details
- send email to applicant inviting to create password
=> Re-jig the seller signup start screen to be your info

app/main/views/signup.py, requirements.txt
=> Application data entry

app/assets/scss/_briefresponse.scss, app/assets/scss/application.scss, app/templates/components/pricing_aud.html, app/templates/components/text.html, app/templates/components/textfield_list.html
Horrible hard-coded margins I know
=> hacked spacing on form fields

app/assets/scss/gov-au-ui-kit/_typography.scss, app/templates/main_template.html
=> Use system fonts

app/templates/_footer.html
This pull request updates footer links so they point to the new Zendesk pages.
Addresses MAR-3320
=> [Footer] Update terms of use, privacy, security, disclaimer and copyright links

app/templates/main_template.html
=> [a11y] Make skip to link content consistent with other front-ends
